Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
base_dir = pjoin(os.environ['HOME'], 'Documents/Kanold')
processed_dir = pjoin(base_dir, 'python_processed')

nb_std = 1
h_load_file = pjoin(processed_dir, "organized_nb_std={:d}.h5".format(nb_std))

run_dir = pjoin(base_dir, 'results/svm/v1_l1_full')
df_all = load_dfs(run_dir)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-b21733a002bd>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0mrun_dir[0m [0;34m=[0m [0mpjoin[0m[0;34m([0m[0mbase_dir[0m[0;34m,[0m [0;34m'results/svm/v1_l1_full'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mdf_all[0m [0;34m=[0m [0mload_dfs[0m[0;34m([0m[0mrun_dir[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/Dropbox/git/A1ToneDiscrimination/utils/generic_utils.py[0m in [0;36mload_dfs[0;34m(load_dir)[0m
[1;32m     20[0m         [0;32mreturn[0m [0mnext[0m[0;34m([0m[0mfilter[0m[0;34m([0m[0mre[0m[0;34m.[0m[0mcompile[0m[0;34m([0m[0mpattern[0m[0;34m)[0m[0;34m.[0m[0mmatch[0m[0;34m,[0m [0mfile_list[0m[0;34m)[0m[0;34m,[0m [0;32mNone[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0;34m[0m[0m
[0;32m---> 22[0;31m     [0mflist[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mlistdir[0m[0;34m([0m[0mload_dir[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     23[0m     [0mcoeffs[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_pickle[0m[0;34m([0m[0mpjoin[0m[0;34m([0m[0mload_dir[0m[0;34m,[0m [0m_get_file[0m[0;34m([0m[0mflist[0m[0;34m,[0m [0;34mr'coeffs_\['[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m     [0mperformances[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_pickle[0m[0;34m([0m[0mpjoin[0m[0;34m([0m[0mload_dir[0m[0;34m,[0m [0m_get_file[0m[0;34m([0m[0mflist[0m[0;34m,[0m [0;34mr'performances_\['[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/hadi/Documents/Kanold/results/svm/v1_l1_full'
FileNotFoundError: [Errno 2] No such file or directory: '/home/hadi/Documents/Kanold/results/svm/v1_l1_full'

