Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 609, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 816, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 633, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 683, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 60 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
from utils.generic_utils import reset_df

load_dir = pjoin(processed_dir, "processed_nb_std={:d}".format(nb_std))
df_all = []
for file_name in tqdm(os.listdir(load_dir)):
    with open(pjoin(load_dir, file_name)) as f:
        df = pd.read_pickle(f.name)
        df_all.append(df)
df_all = pd.concat(df_all)
df_all = reset_df(df_all)
-------------------

