Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pathlib import Path
data_dir = pjoin(base_dir, 'Data')

for path in Path(data_dir).rglob('*.pkl'):
    file = str(path)
    data = pickle.load(open(file, "rb"))
    if data[0]['name'] == "Gabby" and data[0]['date'] == "2016-09-07":
        break

bright_cells = data[0]['bright_cells']
hit = data[0]['hit']
dff = data[0]['dff']

dff = dff[..., bright_cells == 1][:, hit == 1, :]

sns.set_style('whitegrid')
fig, ax_arr = plt.subplots(2, 1, figsize=(10, 8), sharex='col')

ax_arr[0].plot(dff.mean(1))
ax_arr[0].set_ylabel("DFF", fontsize=12)
ax_arr[0].set_title("All bright cells w/ outlier", fontsize=20)

ax_arr[1].plot(dff[..., 1:].mean(1))
ax_arr[1].set_xlabel("Time", fontsize=12)
ax_arr[1].set_ylabel("DFF", fontsize=12)
ax_arr[1].set_title("All bright cells w/o outlier", fontsize=20)

plt.suptitle("name = {}, date = {}".format(data[0]['name'], data[0]['date']), fontsize=20)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-cfe589428d8b>[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m         [0;32mbreak[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;34m[0m[0m
[0;32m---> 10[0;31m [0mbright_cells[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m'bright_cells'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0mhit[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m'hit'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0mdff[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m'dff'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'data' is not defined
NameError: name 'data' is not defined

